before_script:
  - git submodule update --init --recursive

make:
  script:
  - make
  - make opt
  - make release
  - make debug

test:
  script:
  - make test
  - make debug-test
  - make opt-test
  - make release-test

statistics:
  script:
  - make opt-test | grep "Duration per record"
